# Generated by Django 3.1.4 on 2020-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_type',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App')], default='web', max_length=100),
        ),
    ]
