# Generated by Django 3.1.5 on 2021-01-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210103_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio-screenshots')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.portfolio')),
            ],
        ),
    ]
